name: CI

on: pull_request

jobs:
  jjb:
    runs-on: ubuntu-latest
    name: Jenkins Job Builder
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3'
      - name: Restore pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-{{ runner.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          for d in theforeman.org; do
            DIR="."
            ( cd $d && jenkins-jobs -l debug test -r $DIR )
            ( cd $d && jenkins-jobs test -r $DIR --config-xml -o output && find output -name config.xml -exec python ../jenkins-lint.py --xml {} + && rm -rf output )
          done

          for d in centos.org; do
            DIR="jobs"
            ( cd $d && jenkins-jobs -l debug test -r $DIR )
            ( cd $d && jenkins-jobs test -r $DIR --config-xml -o output && find output -name config.xml -exec python ../jenkins-lint.py --xml {} + && rm -rf output )
          done
